Step2 - 볼링 점수판 (그리기)
zuniors/java-bowling pull request #2
Opened 2020-06-22 14:41 UTC by gmlwjd9405

## 기능 요구사항 목록 
### # M (Model)
#### Name
- [x] 이름이 null 이거나 빈 문자열이면 예외가 발생한다.
- [x] 이름은 3글자를 넘길 수 없다.
- [x] 이름을 반환한다.
- [x] 논리적 동치성 비교 

#### Player
- [x] 이름 정보를 가지고 Player 를 생성할 수 있다.
- [x] 참여자의 이름은 3글자를 넘길 수 없다.
- [x] 논리적 동치성 비교 

#### PinCount
: 볼링 수 
- [x] 넘어뜨린 최초 볼링 수가 0 미만이면 예외를 반환한다.
- [x] 총 넘어뜨린 볼링 수가 10 초과면 예외를 반환한다. 
- [x] 최대 개수와 동일한지 여부를 반환한다.
- [x] 최대 개수보다 작은지에 대한 여부를 반환한다.
- [x] 최소 개수와 동일한지 여부를 반환한다.
- [x] 인자의 수 만큼 증가한 볼링 수를 반환한다.
- [x] 볼링수를 반환한다.
- [x] 논리적 동치성 비교 

#### Pins
: 볼링 판에 놓인 볼링
- [x] 넘어뜨린 볼링이 0~10 이외의 값이면 예외를 반환한다.
- 각 상태인지 확인할 수 있다.
    - [x] 스트라이크(strike) : 프레임의 첫번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] 스페어(spare) : 프레임의 두번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] 미스(miss) : 프레임의 두번째 투구에서도 모든 핀이 쓰러지지 않은 상태
- 각 상태에 해당하는 넘어진 핀의 개수를 문자열로 반환한다.
    - [x] 거터(gutter)
    - [x] 숫자(Hit)

#### FrameNumber
: 각 프레임 번호 
- [x] 프레임 번호가 1~10 이외의 숫자면 예외를 반환한다.
- [x] 마지막 프레임이면 return true
- [x] 다음 프레임 단계 만큼 증가한 프레임 번호를 반환한다.
- [x] 논리적 동치성 비교 

#### Frames
: 프레임 리스트
- [x] 처음 생성했을 때 NormalFrame 을 리스트에 추가한다.
- [ ] 공을 던진 후 변경된 상태를 가지는 프레임을 추가한다. check
    - Hit -> Spare 이면 1개
    - Strike -> Strike 면 2개
    - Strike -> Hit -> Strike 면 2개
- [x] 인자로 받은 프레임을 프레임 리스트에 추가할 수 있다. 
- [x] 현재 프레임의 게임 종료 상태를 반환한다.
- [x] 인자로 받은 프레임과 현재 프레임 번호가 동일한지 여부를 판단한다.
- [x] 현재 프레임 번호를 반환한다.
- [x] 모든 프레임의 상태값을 반환한다. check

#### Frame
: 프레임에 대한 추상 클래스
- [x] 공통 기능: 현재 프레임과 동일한 프레임은 Frames 에 추가하지 않는다. (상태값만 업데이트)

#### NormalFrame
: 1~9 번 프레임 
- [x] 쓰러진 공에 따라 상태값이 변경된다.
    - 하나의 상태값을 가진다.
- [x] 종료 상태가 되면 다음 프레임을 반환한다.
- [x] 진행 상태면 자기 자신을 반환한다.
- [x] 게임 종료가 될 수 없다.
- [x] 자신의 프레임 번호를 반환할 수 있다.
- [x] 자신의 상태값을 반환할 수 있다.  
    - check

#### FinalFrame 
: 마지막 10 번 프레임 
- [x] 처음 생성 시에 준비 상태값(Ready)을 하나 가진다.
    - 여러 개의 상태값을 가진다.
- [x] 현재 상태가 종료 상태의 경우 상태값을 추가한다.
- [x] 현재 상태가 진행 상태의 경우 현재 상태를 제거하고 새로 던진 볼링공의 상태를 추가한다. 
- 게임의 종료 여부를 판단한다.
    - [x] e.g. size 3개
        - x|x|x : (ready) -> strike -> strike -> strike
    - [x] e.g. size 2개, Spare 포함
        - 9|/|x (ready -> hit) -> spare -> strike
        - 9|/|2 (ready -> hit) -> spare -> hit
    - [x] e.g. miss 
        - 5|1 (ready -> hit) -> miss 
        - x|5|1 (ready) -> strike -> miss
- [x] 자신의 프레임 번호(10)를 반환할 수 있다.
- [x] 자신의 상태값을 반환할 수 있다.  

#### StateFactory
: 볼링 핀 상태값을 관리
- [x] 준비 상태인 Ready를 반환한다.
- [x] 준비 상태인 Ready에서 넘어트린 볼링핀의 개수에 해당하는 상태를 반환한다. 

#### State
: 볼링 결과 상태에 대한 인터페이스

#### Finished
: 한 프레임의 종료 조건을 만족하는 상태에 대한 추상 클래스
- [x] 해당 상태에서 공을 굴리면 예외를 반환한다.
- [x] 종료 조건을 만족한다. (return true)
- **Miss**: 프레임의 두번째 투구에서도 모든 핀이 쓰러지지 않은 상태
    - [x] 해당 상태를 가질 수 없으면 예외 반환
    - [x] Miss 상태이므로 return true 
    - [x] "-|-", "2|3" 문자열 상태 반환 
- **Spare**: 프레임의 두번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] 해당 상태를 가질 수 없으면 예외 반환
    - [x] Miss 상태가 아님을 반환
    - [x] "9|/", "-|/" 문자열 상태 반환 
- **Strike**: 프레임의 첫번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] Miss 상태가 아님을 반환
    - [x] "x" 문자열 상태 반환 

#### Running
: 한 프레임에서 아직 진행 중인 상태에 대한 추상 클래스
- [x] 종료 조건을 만족하지 않는다. (return false)
- [x] Miss 상태가 될 수 없다. (return false)
- **Hit**: 0~9개의 핀을 쓰러트린 상태 
    - [x] 해당 상태를 가질 수 없으면 예외 반환
    - [x] 두번째 투구에서 나머지 볼링 핀이 모두 넘어지면 Spare 반환
    - [x] 두번째 투구에서 볼링 핀이 1개라도 남아있으면 Miss 반환
    - [x] "2 ", "- " 문자열 상태 반환 
- **Ready**: 볼링을 던지기 전의 상태 
    - [x] 첫 투구에 10개가 넘어지면 Strike 반환
    - [x] 첫 투구에 10개 미만의 볼링 핀이 넘어지면 Hit 반환
    - [x] "" 문자열 상태 반환 

#### BowlingGame
: 여러 볼링 프레임으로 게임을 구성 
- 게임의 종료 여부를 판단한다.
    - [ ] NormalFrame 의 경우 종료될 수 없다.
    - [ ] FinalFrame 의 종료 조건과 동일 
- [ ] 현재 프레임의 번호를 반환한다.
- [ ] 프레임의 결과값을 반환한다.

#### FrameResult
: 볼링 상태에 대한 결과값 
- [x] 상태 문자열 값이 null 또는 빈 문자열이면 예외를 반환한다.
- [x] 상태값 문자열을 반환한다.
- [x] 논리적 동치성 비교 

### # V (View)
#### InputView
- [x] 참여자의 이름 문자열로 입력받는다. 
- [x] 넘어뜨린 볼링수를 입력받는다.

#### ResultView
- [x] 기본 볼링 결과판을 출력한다.
- [x] 입력한 볼링수에 따른 매 프레임의 결과값을 출력한다.

2020-06-22 18:24 UTC, nokchax requested changes
😲😲😲 wow... 어렵다더니... 엄살이었어...ㅋㅋㅋ
구조도 깔끔하구 테스트 코드도 꼼꼼하게 잘짰네요 💯💯 
두 세번 짜본 제 코드랑 비슷해서 리뷰하면서 놀랬어요... 헣헣
물론 세세한것까지 코멘트를 남겨서 리뷰량은 많지만요ㅋㅋㅋㅋ
몽롱한 상태로 달아서 이해가 잘 안가는 코멘트가 있을수 있으니 
모르겠는건 고민 많이 하지말구 물어봐요😄 

이래저래 힘들었을텐데 고생했어요👏👏👏 며칠만 더 힘냅시다!

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/BowlingApplication.java
> +            ResultView.printShape(bowlingGame.getFrameResults(), player);
지금은 한명의 플레이어만 있어서 그런거겠지만, 
프레임과 플레이어가 따로 움직이는게 조금 어색한거 같아요 😅 
추후에 나아질거라 생각합니다

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/BowlingGame.java
> +    public static BowlingGame of() {
전반적으로 정적 팩토리 메서드에 관한 코멘튼데요
parameter 가 없으므로 init 혹은 newInstance 같은 네이밍이 좋을거 같아요
최근에 제가 리뷰 받으면서 공유 받은 메소드 네이밍 관련 [문선](https://docs.oracle.com/javase/tutorial/datetime/overview/naming.html)데 참고해보세요 :)

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/dto/FrameResult.java
> +public class FrameResult {
아래에도 써놓겠지만, 비즈니스 로직을 담당하는 객체와 뷰는 분리 되어야해요 잊지말아요 😢 
FrameResult에서 이미 보여줘야할 string을 가지고 있는게 아니라,
Frame에 대한 정보를 가지고, 그려주는 로직을 통해서 결과를 보여줘야해요 !

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    private final LinkedList<State> states = new LinkedList<>();
wow!😲 마지막 스테이트에 접근하기 편하게 하기 위해 사용하셨군요 👍💯 
다른 용도가 아니라 마지막 스테이스에 접근하기 위한거라면 stack도 괜찮을거 같아요,
리스트 보다 마지막 인자에 좀 더 집중하고 있다는 직관성도 줄수 있구요 😄 
stream을 사용해도 먼저 넣은 값부터 차례대로 루프를 돌리수도 있어요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    private static final int MAX_COUNT = 3;
max count 👍

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    public FinalFrame bowl(final PinCount hitCount) {
저는 마지막 프레임에  대한 로직도 state로 빼서 마지막 프레임에 대한 추가적인 state가 생겼는데, 
마지막 프레임 내부에서 처리하는것도 좋아보이네요 👍

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        this.states.add(currentState.bowl(hitCount));
updateState() 같은 함수로 추출하면 가독성이 더 올라갈거 같아요 😃

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (currentState.isFinish()) {
조금 애매한 리뷰이긴 한데, isFinish()가 strike, spare, miss를 표현하는거라 miss인 경우는 혼동을 줄 수 있는거 같아요. 
외부에서 miss인경우는 게임이 끝났다고 판단되어서 이 로직으로 들어오지 않겠지만, strike와 spare를 표현하는 (모든 핀이 넘어진 상황) isCleanState() 같은 함수를 만들어 사용하는건 어떨까요?

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return this.isEndedBonusBowl() || getLastState().isMiss();
good 👍👍

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    }
개인적으로 아랫줄 이해하는데 조금 시간이 걸렸어요 😭😭 
state.size() == MAX_COUNT 는 스트라이스 세번 연속인 경우,
states.stream.anyMatch(Spare.class::isInstance) && states.size() == COMMON_COUNT 는 strike sapre 혹은 spare 이후 아무 상태(래디 제외) 를 표현한거 같은데.

결국에는 마지막 프레임이 끝났다는걸 표현하는거잖아요? 그러면 아래같은 표현은 어떨까요?
```
마지막 프레임이 끝날조건
1. 한번 던져서 끝나는 경우 : 없음
2. 두번 던져서 끝나는 경우 : miss
3. 세번 던져서 끝나는 경우 : XXX or X?? or ?/- ? 등등 어쨌든 총 3번 던지는 경우
```
이걸 간단하게 표현하면 `마지막 상태가 miss`이거나 `총 3번 던지면` 마지막 프레임이 끝났다고 볼수 있겠죠?
힌트는 여기까쥐 나머지는 고민해보세요 😛

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/Frame.java
> +    abstract int getNo();
getFrameNo() 처럼 명확하게 하는건 어떨까요?

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/Frame.java
> +    }
여기는 혼란을 가중시키는 코드, 자세한건 아래 써둘게요!

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FrameNumber.java
> +public class FrameNumber {
전반적으로 PinCount 클래스에 남긴 코멘트를 참고해서 리팩토링 해보세요 :)

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/FrameNumber.java
> +    public FrameNumber increase() {
여기는 `increase()` 라는 함수명이 어울리네요 👍

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/Frames.java
> +        frame.addFrame(this);
currentFrame의 상태를 물어서 끝난 상태라면 frames.add() 해주던지,
아니면 무조건 currentFrame().createNextFrame(frames)호출후 프레임 내부에서는 프레임이 끝난 조건에서만 frames에 추가하는 식으로 하는게 이해하기 편할거 같아요. 😢 
이렇게 된 근본적인 원인은 아래에 써둘게요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/Frames.java
> +    }
내부에서 직접 불러올 필요없이, frames.size() 하면 되지 않을까요?

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    }
메소드명은 bowl인데 내부에서 하는 일은 공을 굴려서 핀을 쓰러뜨리는 것에 더해서
`프레임을 생성하고 넘겨주는 일` 까지 하고있어요, 프레임 생성에 대한 판단은 frames에서도 frame에서도 할 수있지만, 
적어도 bowl이라는 함수에서는 분리해 내야 할 것 같아요. 😢 다음 프레임 생성에 대한 방식은 위 코멘트에 써뒀어요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    }
Frame 에서 false를 리턴하도록 구현하고 FinalFrame에서만 오버라이드 하는게 낫지 않을까요?

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/pin/PinCount.java
> +public class PinCount {
핀숫자 까지 래핑하다니 👍

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/pin/PinCount.java
> +    public static PinCount of(final int count) {
pin count는 0~10까지 한정적인 범위이고 한정적 개수로 표현 가능 하니까
매번 객체를 생성하지 말구 미리 풀을 만들어두고 사용하는건 어떨까요? 🤔

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/pin/PinCount.java
> +    private void validRange(final int count) {
validateRange() 가 좀 더 어울리는 표현 같아요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/pin/PinCount.java
> +    public PinCount increase(final PinCount pinCount) {
두 카운트의 합이니까 increase 보다는 add 나 sum이 어울리는 표현같아요 😓

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/player/Player.java
> +public class Player {
플레이어와 frames 는 같이 움직여야하는 객체들 아닐까요? 
나중에 플레이어가 늘어나면 두 객체들 간의 싱크 맞추는일이 힘들어질거 같아요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/State.java
> +public interface State {
😲😲😲😲😲😲😲😲
💯💯💯💯💯💯💯💯
대단스..

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/State.java
> +    String getDesc();
도메인에 view과 관련된 로직이 혼재되어있네요, view와 business로직의 분리 잊지 마요 😢

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/StateFactory.java
> +public class StateFactory {
이 클래스는 개인적으로 불필요하다고 생각해요
아마 마지막 프레임에서 hit하는 것 때문에 추가된거 같기두 한데 🤔 
마지막 프레임에서 공을 한번 굴리고나서 -> 스트라이크나 spare상태라면 ready상태의 state를 추가하는 방식으로 구현해보면 어떨까요? 그러면 그냥 마지막 상태값만 꺼내서 bowl해주기만 하면 될텐데

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/StateFactory.java
> +public class StateFactory {
아 정신이 몽롱해서 표현을 잘 못하겠닼ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
의미전달이 잘 안된거 같으면 물어봐요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Finished.java
> +        throw new UnsupportedOperationException();
💯

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Spare.java
> +    private final Pins secondPins;
spare의 경우에는 firstPin과 secondPin의 합이 핀의 총합과 같으니까 secondPin은 필요없겠죠?
firstPin만으로 추론할 수 있으니까요 :)

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Spare.java
> +    }
isMiss()가 여기저기서 많이 보이는데, 추상 클래스에서 false로 선언해두고 
miss 클래스에서만 true로 오버라이드 하는게 어떨까요?
지금 구조에서는 state를 인터페이스가 아니라 추상클래스로 바꾸는게 맞겠네요 :)

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Strike.java
> +public class Strike extends Finished {
스트라이크는 항상 같은 객체를 사용해도 무방할거같아요, 싱글톤을 적용해보는게 어떨까요?

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/running/Hit.java
> +public class Hit extends Running {
개인적으로 HIT라는 클래스명은 준비 단계가 아닌 모든 상태에 해당할 수 있는 표현 같아요 더 좋은 표현 없을까요??
FirstHit 라던가... 저는 running이라고 하긴했는데.. 이 상태에 딱 맞는 네이밍은 아직도 못찾겠네요 😅

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/domain/state/running/Ready.java
> +    }
ready 상태도 싱글턴을 적용할 수 있을거 같네요

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/view/InputView.java
> +        return Integer.parseInt(SCANNER.nextLine());
```suggestion
        return Integer.parseInt(inputString(message));
```
재활용하기!

2020-06-22 18:24 UTC, nokchax commented on src/main/java/bowling/view/ResultView.java
> +    private static final String FRAMES_HEADER =
프레임 수가 늘어나게 된다면 변경이 필요하겠군요😥 
변화에 유연한 코드를 짜도록 해봅시다. 
모든건 변경될 수있다는 생각으로 짜면 편하더라구요.. 물론 짜기는 귀찮지만 😞

2020-06-22 18:24 UTC, nokchax commented on src/test/java/bowling/domain/frame/FramesTest.java
> +    public void isGameOver() {
👍 👍

2020-06-23 02:15 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/state/finish/Spare.java
> +    }
State 인터페이스의 구현체인 Finished 추상 클래스에도 isMiss 메서드를 재정의해서 다른 클래스에서의 중복 재정의를 삭제하였습니다.

여전히 Finished 와 Running 클래스에는 동일한 isMiss 메서드 재정의가 되어 있지만, State 를 추상 클래스로 변경하여 연속적인 상속 구조(부모-자식 관계)를 갖는 것보다 다형성을 이용한다는 측면에서 인터페이스로 두는 것이 낫다고 생각되어, 현재 구조는 유지했습니다. :) 😄

2020-06-23 02:18 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Spare.java
> +    }
오옹 좋습니다! 그러면 State를 구현한 추상 클래스 CommonState같은걸 두는건 어떨까요?
꼭 해보라는게 아니라 이런 방법도 있다는 차원에서 말씀드려요 😄

2020-06-23 02:19 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/state/running/Hit.java
> +public class Hit extends Running {
너무 어려운 네이밍... ㅠㅠ 😢

2020-06-23 02:23 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/state/finish/Spare.java
> +    }
오오! 네넹ㅎㅎㅎ 
그것도 하나의 방법이겠네요!! 👍

2020-06-23 05:06 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/Frames.java
> +    }
`frames.size()` 와 `getCurrentFrame().getNo()` 의 의미가 다르다고 생각합니다.!
예를 들어, frames 에 2개의 Frame 이 들어 있지만 Frame 의 no는 2번이 아닐 수도 있지 않을까요...?
그리고 보여지는 의미 상으로도 **현재 프레임의 넘버를 가지고 오겠다.** 는 의미에서는 더 가독성이 좋은 것 같습니다.ㅎㅎ

2020-06-23 05:12 UTC, nokchax commented on src/main/java/bowling/domain/frame/Frames.java
> +    }
👍👍👍 충분히 설명됐어요ㅎㅎ 좋습니다!

2020-06-23 06:23 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    private final LinkedList<State> states = new LinkedList<>();
오오ㅎㅎ 그러네요! Stack 자료형으로 변경해보겠습니다ㅎㅎㅎ 👍

2020-06-23 09:36 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/Frames.java
> +        frame.addFrame(this);
1) bowl 로 인한 상태 변경
2) 상태에 따른 다음 프레임 생성

두 부분을 분리했더니 이해하기가 확실히 쉬워진 것 같아요!! 👍 👍

2020-06-23 09:38 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/Frame.java
> +    }
공을 굴린 후 상태 변경 행위와 다음 프레임 생성 행위를 분리했더니 자연스럽게 구현체에서 해당 메서드를 재정의하도록 변경되네요. 😄

2020-06-23 11:01 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    }
playCount 를 하나 두어 마지막 프레임 게임 횟수를 체크하는 걸로 변경해봤습니다!
변경한 코드 보시고 이상한 부분 있으면 또 피드백 주세요~ㅎㅎ 👍 😄 👍

2020-06-23 11:12 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/state/StateFactory.java
> +public class StateFactory {
hmm.. 이 부분은 조금 고민되네욯ㅎㅎ
1. `StateFactory`를 통해서 게임 시작 시(보너스 프레임도 포함), 초기화 상태값에 대한 관리를 한 눈에 하기 쉽다는 점에서 좋다(모든 시작점은 Factory의 메서드로 시작)고 생각되기도 하고
2. 이미 `Ready`라는 상태가 게임 준비 상태이기 때문에 의미를 충분히 가지고 있다고 볼 수도 있을 거 같아서요..

```java
if (currentState.isFinish()) {
    // states.push(StateFactory.hit(hitCount));
    states.push(Ready.getInstance().bowl(hitCount));
    return;
}
```

2020-06-23 11:22 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (currentState.isFinish()) {
조금 더 타이트하게 조건을 준다는 의미에서 좋을 거 같네요! ㅎㅎㅎ 👍

2020-06-23 11:39 UTC, nokchax commented on src/main/java/bowling/domain/state/StateFactory.java
> +public class StateFactory {
제 의도가 잘 전달이 안 됐을수도 있을거 같아서 코드로 설명해 볼게요 ㅎㅎ
```java
    @Override
    public void bowl(final PinCount hitCount) {
        increasePlayCount();
        updateLastState(getLastState().bowl(hitCount));
        giveMoreChange();
    }
    
    private void giveMoreChange() {
        if (getLastState().isFinish()) {
            states.push(Ready.getInstance());
        }
    }
```
요런식으로 StateFactory.hit() 호출을 없앨수 있지 않을까 해서 말씀드렸던 거예요 :)
사실 hit후 바로 state를 넣어주느냐 아니면 hit할때 판단 후 넣어주느냐 차이라서, 희정님이 선호하는 방식으로 하셔도 무방합니다 😄

2020-06-23 12:50 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/state/StateFactory.java
> +public class StateFactory {
아하~! 제가 리뷰 의도를 잘못 이해했네요ㅎㅎㅎㅎ
오! 코드로 확인해보니 bowl() 호출을 분기 없이 하는게 더 가독성이 좋아보이네여!!ㅎㅎㅎ
변경해보도록 하겠습니다~ 👍

2020-06-24 10:42 UTC, nokchax approved these changes
고생했어요👏👏👏 리팩토링 깔끔하게 잘했네요, 코드가 더욱 간결해졌슴돠 😄💯 
언제나 느끼는 거지만 테스트도 꼼꼼하게 잘하셨구요, view로직 분리도 구조를 잘 잡아두셨어요 다만,
PinCount 가져올때 미리 변환된 String이 아니라 int로 가져와서 변환해주면 완벽할것 같습니다.
핀의 갯수를 표현하는 String 을 반환하는 거 자체가 view로직이 들어간거라고 볼수 있으니까요
요것만 수정합시다 :)
머지는 next-step쪽 머지 후에 하도록 할게요!

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/dto/StateConverter.java
> +public enum StateConverter {
아주 잘 분리하셨습니다 :) 👏👏👍💯

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/dto/StateConverter.java
> +                .converter.apply(stateDto);
.은 한줄에 하나만!

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/dto/StateDto.java
> +        return this.state.getFirstPins().getDescOfHitCount();
여기두

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    private int playCount;
💯

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (getLastState().isCleanState()) {
이거 혹시 frame상태가 end 가 아니라면 ready상태가 하나 더 들어갈수도 있을거 같은데, 
확인 한 번 해보세요 ㅎㅎ 로직상으로 큰 문제가 될거같지는 않지만 😅

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return isEndedBonusBowl() || getLastState().isMiss();
깔끔해져서 좋네요 👍

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Strike.java
> +    private static class InnerInstanceClass {
👍

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Finished.java
> +    }
공통이 될만한 코드를 미리 선언해 두셨네요 훌륭한 처리! ㅎㅎ 💯

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    void addFrame(Frames frames) {
아무것도 하지 않는경우에는 주석으로라도 설명을 달아주는게 자신을 위해서도 좋더라구요 ㅋㅋ
내가 짠 코드라도 나중에 코드보면 헷갈릴 때가 있어요
```java
// do nothing
```

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/dto/StateConverter.java
> +public enum StateConverter {
근데 약간 아쉬운 부분이 StateDto 에서 getPins할때 string값을 가져오는 부분인데요, 이런 부분은 숫자를 미리 문자열로 바꿔서 보내주는거라고 봐야해서 완벽히 분리했다고 볼수 없어요.

희정님은 금방 고치실거 같긴하지만 시간을 절약하기 위해서 제가 썼던 방법을 공유해볼게요
```java
public enum Symbol {
    ZERO(0, "-"),
    TEN(10, "X");

    private static final Map<Integer, String> SYMBOLS =
            Arrays.stream(values())
                    .collect(Collectors.toMap(Symbol::getNumber, Symbol::getSymbol));
    private final int number;
    private final String symbol;

    Symbol(final int number, final String symbol) {
        this.number = number;
        this.symbol = symbol;
    }

    public static String convert(final int number) {
        return SYMBOLS.getOrDefault(number, String.valueOf(number));
    }

    private int getNumber() {
        return number;
    }

    private String getSymbol() {
        return symbol;
    }
}
```

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/dto/StateConverter.java
> +public enum StateConverter {
이후에 getFirstPins는 int값을 가져오게 만들고
StateDto.getFirstPins -> Symbol.convert(stateDto.getFirstPins()) 로 변경 하는게 맞지 않을까요?

2020-06-24 10:42 UTC, nokchax commented on src/main/java/bowling/domain/pin/Pins.java
> +    public String getDescOfHitCount() {
요거를 삭제하도록 합시다!

2020-06-24 10:46 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    void addFrame(Frames frames) {
오호! 꿀팁 감사합니다.ㅎㅎㅎ 👍

2020-06-24 10:48 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/dto/StateConverter.java
> +                .converter.apply(stateDto);
흠... 뭔가 converter.apply() 가 한 묶음이어야 될 거 같은 느낌인데... 
우선 규칙이니 반영하도록 하겠숨다! 👍

2020-06-24 10:51 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/dto/StateConverter.java
> +public enum StateConverter {
오!ㅋㅋㅋㅋ 이렇게 하면 더 간단해지겠네요~ 👍 
적용해보겠습니다.

2020-06-24 11:07 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (getLastState().isCleanState()) {
로직상으로 문제는 되지 않는데, 
출력하는 부분에서 joining 할 때 좀 다르게 출력돼서 Ready 상태를 제외하고 출력하도록 구현했습니다!
```java
public String getDesc() {
    return this.stateDtos.stream()
            .filter(stateDto -> !stateDto.isReady()) // Ready 상태 제외 
            .map(StateConverter::convertToDesc)
            .collect(Collectors.joining(StateExpression.DELIMITER));
}
```

2020-06-24 13:51 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (getLastState().isCleanState()) {
전체적으로 래디 상태가 문제였나요?? 마지막 프레임 에서만 문제라면 giveBonusBowl() 메소드에서 넣어줄때 !isFinishded()  조건을 추가하면 스트림에서 필터처리 안해두 될거같은데 :thinking:

2020-06-24 13:58 UTC, nokchax commented
:clap: :clap: :tada: 이제 한단계 남았네요 ㅋㅋㅋㅋ 이번 단계에서 구조를 잘 잡아둬서 아주 어렵지는 않을거예요, 파이팅!

2020-06-26 12:46 UTC, merged