Step3 - 볼링 점수판 (점수 계산)
zuniors/java-bowling pull request #3
Opened 2020-06-30 09:35 UTC by gmlwjd9405

## 기능 요구사항 목록 
### # M (Model)
#### Name
- [x] 이름이 null 이거나 빈 문자열이면 예외가 발생한다.
- [x] 이름은 3글자를 넘길 수 없다.
- [x] 이름을 반환한다.
- [x] 논리적 동치성 비교 

#### Player
- [x] 이름 정보를 가지고 Player 를 생성할 수 있다.
- [x] 참여자의 이름은 3글자를 넘길 수 없다.
- [x] 논리적 동치성 비교 

#### PinCount
: 볼링 수 
- [x] 넘어뜨린 최초 볼링 수가 0 미만이면 예외를 반환한다.
- [x] 총 넘어뜨린 볼링 수가 10 초과면 예외를 반환한다. 
- [x] 최대 개수와 동일한지 여부를 반환한다.
- [x] 최대 개수보다 작은지에 대한 여부를 반환한다.
- [x] 최소 개수와 동일한지 여부를 반환한다.
- [x] 인자의 수 만큼 증가한 볼링 수를 반환한다.
- [x] 볼링수를 반환한다.
- [x] 논리적 동치성 비교 

#### Pins
: 볼링 판에 놓인 볼링
- [x] 넘어뜨린 볼링이 0~10 이외의 값이면 예외를 반환한다.
- 각 상태인지 확인할 수 있다.
    - [x] 스트라이크(strike) : 프레임의 첫번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] 스페어(spare) : 프레임의 두번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] 미스(miss) : 프레임의 두번째 투구에서도 모든 핀이 쓰러지지 않은 상태
- [x] 각 상태에 해당하는 넘어진 핀의 개수를 반환한다.
- [x] 현재 볼링 핀의 개수에 두 번째 볼링 핀의 개수를 더하여 핀 개수를 반환한다.
- [x] 인자로 넘어온 점수에 해당 볼링 핀의 개수를 더한 점수를 반환한다.

#### PinExpression
: 볼링 핀에 대한 표현식
- [x] gutter(0개) 는 "-"
- [x] strike(10개) 는 "X"
- [x] 1~9개 숫자는 "1~9"

#### FrameNumber
: 각 프레임 번호 
- [x] 프레임 번호가 1~10 이외의 숫자면 예외를 반환한다.
- [x] 마지막 프레임이면 return true
- [x] 다음 프레임 단계 만큼 증가한 프레임 번호를 반환한다.
- [x] 논리적 동치성 비교 

#### Frames
: 프레임 리스트
- [x] 처음 생성했을 때 NormalFrame 을 리스트에 추가한다.
- [x] 공을 던진 후 변경된 상태를 가지는 프레임을 추가한다.
    - Hit -> Spare -> Ready 이면 2개
    - Strike -> Strike -> Ready 면 3개
    - Strike -> Hit 면 2개
- [x] 인자로 받은 프레임을 프레임 리스트에 추가할 수 있다. 
- [x] 현재 프레임의 게임 종료 상태를 반환한다.
- [x] 인자로 받은 프레임과 현재 프레임 번호가 동일한지 여부를 판단한다.
- [x] 현재 프레임 번호를 반환한다.
- [x] 모든 프레임의 상태값을 반환한다. 

#### Frame
: 프레임에 대한 추상 클래스
- 해당 프레임의 점수를 반환한다.
- 여분의 보너스 점수를 해결하기 위한 추가적인 점수를 계산하여 반환한다.

#### NormalFrame
: 1~9 번 프레임 
- [x] 쓰러진 공에 따라 상태값이 변경된다.
    - 하나의 상태값을 가진다.
-  상태값이 isFinal(Strike, Spare, Miss) 의 경우 새로운 Frame 생성하여 반환한다.
    - [x] 현재 프레임의 상태가 종료 상태면 다음 프레임을 생성하여 반환한다.
    - [x] 현재 프레임의 상태가 진행 상태면 현재 프레임을 반환한다.
-  프레임 리스트에 프레임을 추가한다.  
    - [x] 현재 프레임의 상태가 종료 상태면 다음 프레임을 추가한다.
    - [x] 현재 프레임의 상태가 진행 상태면 추가하지 않는다.
- [x] 게임 종료가 될 수 없다.
- [x] 자신의 프레임 번호를 반환할 수 있다.
- [x] 자신의 상태값을 반환할 수 있다.  
- [x] 해당 프레임의 점수를 반환한다.
    - 종료 상태가 아니거나 nextFrame 이 null 인 경우 UN_SCORE 를 반환한다.
    - 여분의 보너스 개수가 남아있지 않으면 score 를 반환한다.
    - 여분의 보너스 개수가 남아있으면 다음 프레임의 값에서 추가적인 계산을 수행한다.
- [x] 여분의 보너스 점수를 해결하기 위한 추가적인 점수를 계산하여 반환한다.
    - 상태에 맞는 여분의 보너스 만큼의 점수를 반환한다.
    - 여분의 보너스 개수가 남아있지 않으면 score 를 반환한다.

#### FinalFrame 
: 마지막 10 번 프레임 
- [x] 처음 생성 시에 준비 상태값(Ready)을 하나 가진다.
    - 여러 개의 상태값을 가진다. (최대 3개)
- [x] 현재 상태가 종료 상태의 경우 상태값을 추가한다.
- [x] 현재 상태가 진행 상태의 경우 현재 상태를 제거하고 새로 던진 볼링공의 상태를 추가한다. 
- 게임의 종료 여부를 판단한다.
    - [x] e.g. size 3개
        - x|x|x : (ready) -> strike -> strike -> strike
    - [x] e.g. size 2개, Spare 포함
        - 9|/|x (ready -> hit) -> spare -> strike
        - 9|/|2 (ready -> hit) -> spare -> hit
    - [x] e.g. miss 
        - 5|1 (ready -> hit) -> miss 
        - x|5|1 (ready) -> strike -> miss
- [x] 자신의 프레임 번호(10)를 반환할 수 있다.
- [x] 자신의 상태값을 반환할 수 있다.  
- [x] 해당 프레임의 점수를 반환한다.
- [x] 여분의 보너스 점수를 해결하기 위한 추가적인 점수를 계산하여 반환한다.

#### State
: 볼링 결과 상태에 대한 인터페이스
- [x] 해당 상태의 점수를 반환한다.
- [x] 여분의 보너스 개수만큼 해당 상태의 점수를 추가하여 반환한다.

#### Finished
: 한 프레임의 종료 조건을 만족하는 상태에 대한 추상 클래스
- [x] 해당 상태에서 공을 굴리면 예외를 반환한다.
- [x] 종료 조건을 만족한다. (return true)
- 첫 번째와 두 번째 투구 결과인 볼링 핀을 반환한다.
- [x] 각 프레임이 가지는 모든 상태값을 반환한다.
- **Miss**: 프레임의 두번째 투구에서도 모든 핀이 쓰러지지 않은 상태
    - [x] 해당 상태를 가질 수 없으면 예외 반환
    - [x] Miss 상태이므로 return true 
    - [x] 첫 번째와 두 번째 투구 결과인 볼링 핀을 반환한다.
- **Spare**: 프레임의 두번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] 해당 상태를 가질 수 없으면 예외 반환
    - [x] Miss 상태가 아님을 반환
    - [x] 첫 번째와 두 번째 투구 결과인 볼링 핀을 반환한다.
- **Strike**: 프레임의 첫번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [x] Miss 상태가 아님을 반환
    - [x] 첫 번째 투구 결과인 볼링 핀을 반환, 두 번째 투구는 반환할 수 없다.

#### Running
: 한 프레임에서 아직 진행 중인 상태에 대한 추상 클래스
- [x] 종료 조건을 만족하지 않는다. (return false)
- [x] Miss 상태가 될 수 없다. (return false)
- 첫 번째와 두 번째 투구 결과인 볼링 핀을 반환한다.
- [x] 각 프레임이 가지는 모든 상태값을 반환한다.
- **FirstHit**: 0~9개의 핀을 쓰러트린 상태 
    - [x] 해당 상태를 가질 수 없으면 예외 반환
    - [x] 두번째 투구에서 나머지 볼링 핀이 모두 넘어지면 Spare 반환
    - [x] 두번째 투구에서 볼링 핀이 1개라도 남아있으면 Miss 반환
    - [x] 첫 번째 투구 결과인 볼링 핀을 반환, 두 번째 투구는 반환할 수 없다.
- **Ready**: 볼링을 던지기 전의 상태 
    - [x] 첫 투구에 10개가 넘어지면 Strike 반환
    - [x] 첫 투구에 10개 미만의 볼링 핀이 넘어지면 Hit 반환
    - [x] 첫 번째와 두 번째 투구 결과를 모두 반환할 수 없다.

#### BowlingGame
: Player와 여러 볼링 프레임으로 게임을 구성 
- 게임의 종료 여부를 판단한다.
    - [ ] NormalFrame 의 경우 종료될 수 없다.
    - [ ] FinalFrame 의 종료 조건과 동일 
- [ ] 현재 프레임의 번호를 반환한다.
- [ ] 프레임의 결과값을 반환한다.

#### StateDto
: State DTO (볼링 상태값)
- [x] 상태값이 null이면 예외를 반환한다.
- [x] 상태값의 클래스 타입을 반환한다.
- [x] 상태값의 타입이 Ready 인지 여부를 확인할 수 있다.
- [x] 첫 번째 볼링핀의 출력값을 반환한다.
- [x] 두 번째 볼링핀의 출력값을 반환한다.

#### StateDtos
: 한 프레임에서의 모든 상태값들 
- [x] 볼링 상태값 리스트 인자가 null 인 경우 예외를 반환한다.
- [x] 각 프레임의 모든 상태값을 출력값으로 변환하여 반환한다.
    - FinalFrame 의 경우 상태가 최대 3개까지 가능하다.
    - NormalFrame 의 경우, 상태값은 무조건 1개이다.
    - FinalFrame 에서 Ready 상태는 출력에서 제외한다.

#### StateConverter
: 볼링 상태값을 출력값으로 변환
- [x] 특정 상태값을 알맞는 출력값으로 변환한다.
    - [x] **Miss** : "-|-", "2|3" 문자열 상태 반환 
    - [x] **Spare** :  "9|/", "-|/" 문자열 상태 반환 
    - [x] **Strike** :  "x" 문자열 상태 반환 
    - [x] **FirstHit** :  "2", "- " 문자열 상태 반환 
    - [x] **Ready** :  "" 문자열 상태 반환 

#### Score
: 볼링 점수 (점수, 추가적인 보너스 점수 개수)
- [x] 각 점수 클래스 상태값 반환
- [x] 현재 점수에 추가된 점수를 더하고 보너스 점수 개수를 하나 감소한다.
- [x] 현재 점수에 새로 추가된 점수만 추가하여 반환한다.
- [x] 점수를 계산할 수 있는 상태인지 확인한다
    - 여분의 보너스 개수가 0개이고 UN_SCORE가 아닌 상태만 계산 가능
- [x] 해당 점수가 초기 점수 설정(INIT_SCORE)값인지 확인힌다.
- [x] 자신의 점수를 반환한다.
    - 여분의 보너스 개수가 0이 아니면 예외를 반환한다.
- [x] 논리적 동치성 비교 

#### Scores
: 볼링 점수 일급 컬렉션
- [x] 볼링 점수 리스트를 생성
- [x] 해당 프레임의 점수를 리스트에 추가한다. 
    - (여분의 보너스 개수가 0개이고 UN_SCORE가 아닌 상태)가 아닌 경우
    - INIT_SCORE 인 경우
    - 위의 두가지 경우에는 점수를 계산할 수 없다.
- [x] 점수 리스트를 반환한다.

#### ScoreDto
: 볼링 점수 출력용
- [x] ScoreDto 생성
- [x] 볼링 핀의 개수를 반환한다.

### # V (View)
#### InputView
- [x] 참여자의 이름 문자열로 입력받는다. 
- [x] 넘어뜨린 볼링수를 입력받는다.

#### ResultView
- [x] 기본 볼링 결과판을 출력한다.
- [x] 입력한 볼링수에 따른 매 프레임의 결과값을 출력한다.
- [x] 입력한 볼링수에 따른 점수 결과값을 출력한다.

2020-06-30 12:30 UTC, nokchax requested changes
고생했어요. 이제 큰고비 다 넘겼네요 👏👏👏
이미 점수 계산하는 구조는 충분히 좋아서👍👍💯 
큰 변경은 없구요 분기처리를 줄이면 될것 같아요 : )
그리구 테스트 코드는 항상 꼼꼼하게 잘짜지만, 
마지막 프레임에서 점수 계산 미스났던것에 대해 
추가적으로 테스트 작성하면 좋을거 같아요.

모르거나 의미전달이 잘 안된 경우는 물어보세요😃

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/dto/ScoreDto.java
> +public class ScoreDto {
👍

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (getLastState().isCleanState() && !isEndedBonusBowl()) {
점수 계산때문에 추가한 느낌이군여 ㅎㅎ

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        }
음 전체적으로 계산에 대한 분기 문이 많은데,
어차피 dto로 만들때 해당 score가 계산 가능한지 확인(canCalculateScore()) 후에 DTO처리를 하잖아요?
그렇다면 이런 분기는 필요없지 않을까요? 어떤 상태이건 점수 계산이 불가능하다면 처리가 안될테니까요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return states.peek().getScore();
이건 따로 말씀드렸지만 ㅎㅎ 버그유발!

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return score;
good! 저도 이렇게 짰어요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    public Score calculateAdditionalScore(final Score beforeScore) {
addBonusScore 정도로 짧게하면 어떨까요? 메소드명이 약간 긴느낌!

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/Frames.java
> +                .filter(Score::canCalculateScore)
👍

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    private Frame nextFrame;
이렇게 두면 다음 프레임 생성 전에는 null로 있게 되는데,
DummyFrame 클래스를 하나 두는건 어떨까요? 
Frame을 구현하지만 내부적으로는 아무일도 하지 않는 클래스에요
초기화 시에 DummyFrame을 두고, 이 프레임이 끝나면 새 프레임으로 교체식으로요!
그러면 DummyFrame인지를 확인하는 분기분이 없앨수 있겠죠?

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        }
없애도 될 분기분!
로직은 최대한 간결하게

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        }
여기서 묻는것 보다 calculateAdditionalScore() 에서 최초에 확인후 반환하는건 어떨까요?

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        }
이것도 없앱시다!

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        }
```suggestion
        if (score.isZeroOfExtraBonusCount()) {
            return score;
        }
        final Score score = state.calculateScoreForExtraBonusCount(beforeScore);
```
위에 쓴것처럼
이런식으로 하고, 더한 점수가 계산 가능한지 아닌지는 이 다음 프레임으로 넘기는게 좋을거 같아요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    }
분기문이 사라지면 이건 없어도 될 로직 같아요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/score/Score.java
> +public class Score {
👍

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/score/Score.java
> +    public static final Score INIT_SCORE = new Score(ZERO, NOT_ALLOCATED);
둘중 하나만 있어도 될거 같아요, 저같은 경우는 INCALCULABE 이라는  Score 객체를 두고,
기본적으로 Finished 스테이트가 아닌 스테이트는 모두 INCALCULABLE을 리턴하도록 했어요 :)

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/score/Score.java
> +    }
isZero 랑 isAddable 처럼 isCalculabe같은 메소드명이 어떨까요? 
can~~는 할수있다라는 느낌이라서 boolean을 리턴하는 느낌을 주지는 않는거 같아요.

음 그리고 이건 취향차이 일거 같은데, 추출 했을때 한줄짜리 메소드는 따로 추출하지 않아도 되지 않을까요?

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/score/Score.java
> +    }
INIT_SCORE 도 계산 불가능한 영역이라서 canCalculateScore() 에 추가하거나 UN_SCORE로 통합하는게 좋아보여요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/score/Score.java
> +    }
👍

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/score/Scores.java
> +    }
```suggestion
    public void sumScore(final Frame frame) {
        Score score = frame.getScore();

        if (!score.canCalculateScore() || score.isInitScore()) {
            return;
        }

        addScore(score);
    }
    
    private Score lastScore() {
        if (scores.isEmpty()) {
            return Score.valueOf(0, 0);
        }

        return getCurrentScore();
    }

    private void addScore(final Score newScore) {
        Score currentScore = lastScore();
        Score nextScore = currentScore.add(newScore);

        scores.add(nextScore);
    }
```
요런식도 괜찮을거 같아요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Miss.java
> +    }
여기서도 맨 처음에 beforeScore가 계산 가능한지 판단해서 가능하다면 리턴하는 식으로 해야할 필요가 있어요,
그런데 그렇게 되면 분기분이 반복되는 느낌도 있죠? 모든 상태에서 동일한 로직 느낌도 있구요

그래서 state에서 아래처럼 처리하는 것도 한 방법입니다
```java
public Score calculateScoreForExtraBonusCount(Score beforeScore) {
    if (beforeScore.isZeroOfExtraBonusCount()) {
        return beforeScore;
    }

    return calculate(beforeScore);
}
private abstract Score calculate(Score beforeScore) {
    // 더해주는 계산식
}
```

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Spare.java
> +        beforeScore = this.firstPins.sumScore(beforeScore);
여기도 마찬가지!

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/finish/Strike.java
> +        if (beforeScore.isZeroOfExtraBonusCount()) {
여기는 잘 되어있네요

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/running/FirstHit.java
> +        return Score.valueOf(this.firstPins.getHitCount(), Score.ZERO);
FirstHit은 계산 불가능한 상태니까 불가능한것을 표현한 
INIT_SCORE나 UN_SCORE 같은 인스턴스를 리턴해야하지 않을까요?

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/running/FirstHit.java
> +        return Score.valueOf(this.firstPins.getHitCount(), Score.ZERO);
버그를 유발할 수 있어요 🐞

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/running/FirstHit.java
> +        beforeScore = this.firstPins.sumScore(beforeScore);
수정수정

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/running/FirstHit.java
> +        return Score.INIT_SCORE;
말씀드렸지만 INIT_SCORE를 리턴하는 건 역시 버그를 유발할 수 있어요,
점수를 계산하고 못하고는 score 객체의 extraBonusCount로 충분히 구할 수 있으니까
계산된 score를 리턴하는 정도로 합시다

2020-06-30 12:30 UTC, nokchax commented on src/main/java/bowling/domain/state/running/Ready.java
> +        return Score.INIT_SCORE;
여기도 INIT_SCORE가 아닌 beforeScore를 리턴해서 추후에 판단하도록

2020-06-30 12:38 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return states.peek().getScore();
하하하...

2020-06-30 15:30 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/score/Score.java
> +    public static final Score INIT_SCORE = new Score(ZERO, NOT_ALLOCATED);
UN_SCORE 로 통일시키도록 하겠습니다! 👍 😄 👍

2020-06-30 15:42 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/score/Score.java
> +    }
`isZeroOfExtraBonusCount()`는 외부에서 사용하는 메서드이기 때문에 한 줄 짜리 메서드로 구성하였습니다.
음.... 그리고 `isAddableScore()` 메서드는 UN_SCORE 이라는 상수명을 봤을 때는 무엇을 의미하는지 알기 어렵기 때문에 메서드명을 통해 조금 더 쉽게 점수를 계산할 수 있는 경우를 알 수 있다는 장점이 있는 거 같습니다! 😄

2020-06-30 15:47 UTC, nokchax commented on src/main/java/bowling/domain/score/Score.java
> +    }
아하 isAddableScore는 확실히 알아보기 힘들겠네요, 좋슴다 😄 
그런데 isZeroOfExtraBonusCount() 는 canCalculateScore() 로 대체할 수 있지 않을까요??

2020-06-30 16:05 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/state/finish/Miss.java
> +    }
결국 State를 추상 클래스로 변경하게 되네여...ㅎㅎㅎ 
변경해보도록 하겠습니다! 👍

2020-06-30 16:13 UTC, gmlwjd9405 commented on src/main/java/bowling/domain/score/Score.java
> +    }
그렇네요ㅎㅎㅎ 어차피 UN_SCORE 인 경우에도 계산하지 못하니까 각 상태값에서 남은 보너스 개수만 확인하지 않고 `canCalulateCount()` (**isCalculable**로 네이밍 변경) 로 확인하면 될 거 같아요!
```java
    @Override
    protected Score calculateScoreForExtraBonusCount(Score beforeScore) {
        beforeScore = this.firstPins.sumScore(beforeScore);
        if (beforeScore.isCalculable()) { // 
            return beforeScore;
        }
        beforeScore = this.secondPins.sumScore(beforeScore);

        return beforeScore;
    }
```

2020-07-01 12:12 UTC, nokchax approved these changes
고생스!

2020-07-01 12:12 UTC, nokchax commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        if (beforeScore.isCalculable()) {
리뷰는 다음단계에서!

2020-07-01 12:12 UTC, merged